### ISSUE TITLE
Default Less grammar for VS Code

### ISSUE THREAD

**Issue by alexr00** [radium-v/Better-Less#15]
Hello 👋 

I'm a developer on VS Code and I'm looking for a grammar to replace https://github.com/atom/language-less as the default Less grammar in VS Code (https://github.com/microsoft/vscode/issues/171239).

@radium-v, do you have any interest in reviving radium-v/Better-Less and maintaining it as the default Less grammar of VS Code? When VS Code users file issues in https://github.com/microsoft/vscode about Less syntax highlighting I would then copy them over here for you to handle. You can see an example of how that goes over in https://github.com/jeff-hykin/better-cpp-syntax.

Thanks for considering!

**Comment by alexr00** [comment]
@radium-v that's great to hear! Once you feel that the grammar is ready, I'll switch VS Code over to using it in our insiders build for a month or two. After that, I'll let the grammar update go out in the following stable VS Code release.

**Comment by radium-v** [comment]
Hi @alexr00,

After a tumultuous year, I'm just about ready with the extension. I plan to have the next version published sometime this week.

**Comment by alexr00** [comment]
@radium-v that is great news! I'll keep an eye out for the release and try pulling the changes into VS Code.
