### ISSUE TITLE
Support for Svelte syntax highlighting

### ISSUE THREAD

**Issue by tuyuritio** [radium-v/Better-Less#29]
Please select any editor that you're experiencing this issue in.
- Visual Studio Code

Please provide the name/repo of the color scheme package you're using:
- Default Dark+

Please include any packages/extensions you're using which could be conflicting:
- Svelte for VS Code

---

First of all, congratulations on your grammar becoming a built-in grammar in VSCode!

However, there are currently some issues when using Svelte for development:

The normal rendering is shown in the picture:

![image](https://github.com/radium-v/Better-Less/assets/46957197/faa9a268-3cfe-4a5c-942d-5fd7e08fcaa8)

But when I use some Svelte features, things get a bit messy:

![image](https://github.com/radium-v/Better-Less/assets/46957197/c383e40d-6b4d-4d31-893d-b95cff72e3cb)

---
An example would be nice if you can provide one.
```less
p {
    font-size: 20px;

    :global(.test) {
        color: black;
    }
}
```

**Comment by radium-v** [comment]
Hi, thanks for the issue! This is an interesting one - I'm not familiar with `:global()` scoping in CSS Modules.

Does this extension provide a way forward for you? https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

You may need to add custom styles, as described in the Svelte for VS Code documentation: https://github.com/sveltejs/language-tools/blob/HEAD/docs/README.md#adjust-syntax-highlighting-of-svelte-files

If you're still having issues getting this working, let me know.
