### ISSUE TITLE
Highlighting for new properties, values, selectors

### ISSUE THREAD

**Issue by MarekOCLC** [radium-v/Better-Less#30]
Please select any editor that you're experiencing this issue in.
- Visual Studio Code 1.86.1

Please provide the name/repo of the color scheme package you're using:
- Light+

---

Certain properties, values, and selectors are not being highlighted correctly. It seems to be "newer" CSS that has issues. This may not be a comprehensive list, but these are the issues I'm seeing in my projects.

Properties:
- [x] [CSS logical properties and values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values)
  - `block-size | inline-size | max-block-size | max-inline-size | min-block-size | min-inline-size`
  - `margin-block | margin-block-end | margin-block-start | margin-inline | margin-inline-end | margin-inline-start`
  - `padding-block | padding-block-end | padding-block-start | padding-inline | padding-inline-end | padding-inline-start`
  - `border-block | border-block-end | border-block-start | border-inline | border-inline-end | border-inline-start`
  - `border-block-color | border-block-end-color | border-block-start-color | border-inline-color | border-inline-end-color | border-inline-start-color`
  - `border-block-end-style | border-block-start-style | border-block-style | border-inline-end-style | border-inline-start-style | border-inline-style`
  - `border-block-end-width | border-block-start-width | border-block-width | border-inline-end-width | border-inline-start-width | border-inline-width`
  - `border-start-start-radius | border-start-end-radius | border-end-start-radius | border-end-end-radius`
  - `inset | inset-block | inset-block-end | inset-block-start | inset-inline | inset-inline-end | inset-inline-start`
  - `contain-intrinsic-block-size | contain-intrinsic-inline-size`
  - `overflow-block | overflow-inline | overscroll-behavior-block | overscroll-behavior-inline`
- [x] [Gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap)
  - `gap`
  - `row-gap`
- [x] `justify-self`
- [x] `justify-items`
- [x] `text-size-adjust`, `-webkit-text-size-adjust`, `-moz-text-size-adjust`, `-ms-text-size-adjust`
- [x] `text-wrap`, `white-space-collapse`
- [x] #50

Values:
- [x] #41
- [x] #51
- [x] clear `inline-end | inline-start`
- [x] float `inline-end | inline-start`

Selectors: 
- [x] #52

VS Code screenshot
<img width="375" alt="Screenshot 2024-02-12 at 6 17 28 PM" src="https://github.com/radium-v/Better-Less/assets/102601087/c0011792-a831-4003-9800-e7453083d000">

According to [VS Code release notes](https://code.visualstudio.com/updates/v1_86#_new-less-grammar), VS Code 1.86 is now using this repo for Less highlighting, so my issues are being observed in plain VS Code without the Better Less extension installed. I've attempted to remove all other settings or extensions that could be conflicting and am still seeing the issues, but please let me know if I'm mistaken!
See also [VS Code 1.86 Less syntax highlighting not correct - StackOverflow](https://stackoverflow.com/questions/77984498/vs-code-1-86-less-syntax-highlighting-not-correct)

**Comment by leopoldkristjansson** [comment]
I have the same issue using **VS Code Version: 1.86.2 (Universal)**. 

Screenshot from a `.vue` file.

<img width="664" alt="Screenshot 2024-02-16 at 11 22 18" src="https://github.com/radium-v/Better-Less/assets/2579324/276163e7-f71a-436a-ae48-fb47e0bfca06">

**Comment by radium-v** [comment]
#31 adds the logical properties and values. More PRs incoming to address the remaining missing properties.

**Comment by radium-v** [comment]
#34 adds support for `gap` properties.

**Comment by radium-v** [comment]
#35 adds support for `text-size-adjust`, `text-wrap`, and `white-space-collapse` properties and values.

**Comment by radium-v** [comment]
#36 adds support for `justify-self`, `justify-items`, `place-content`, `place-items`, and `place-self`.

**Comment by radium-v** [comment]
#41 tracks `@container` and related properties.

**Comment by radium-v** [comment]
This is now completed and v0.7.0 is released. I don't know when it'll be updated in VS Code, but installing the extension should take priority over the built-in support.
