### ISSUE TITLE
syntax color after a :not directive

### ISSUE THREAD

**Issue by jchautreux** [radium-v/Better-Less#8]
the syntax coloration is deactivate (or weird) after a :not directive that does not contain a ":".

Example:
```
.my-element:not(:first-child) {...} //work perfectly
.my-element:not(.my-class:first-child) {...} //work perfectly
.my-element:not(.my-class) {...} //break the syntax coloration
```

**Comment by radium-v** [comment]
Hi @jchautreux,

Which editor and color scheme are you seeing this error with?

**Comment by jchautreux** [comment]
Sorry, I did not see your question.
So, I use Sublime Text 3 with IR_Black_2 color scheme

**Comment by radium-v** [comment]
So I couldn't find the specific color scheme you're using but I tested with [this one](https://github.com/rmcooper/IR_Black-Theme) and I see that the scheme doesn't apply colors to most of the scopes provided by Better Less.

Can you update to 0.4.0 and inspect the scope? You can do that by moving the cursor to the place that's not highlighting properly and press Command+Option+P to show the scope names.

<img width="752" alt="screen shot 2017-09-07 at 11 08 37 am" src="https://user-images.githubusercontent.com/863023/30171318-aa0fdf0c-93bf-11e7-8d16-e0084647ccd8.png">

**Comment by jchautreux** [comment]
I'm sorry, but after update, this weird behaviour seems to have disappeared

**Comment by radium-v** [comment]
Hooray!
